package me.kolterdyx.compiler

enum class TokenType {
    // Punctuation.
    P_LEFT_PAREN, P_RIGHT_PAREN, P_LEFT_BRACE, P_RIGHT_BRACE,
    P_COMMA, P_DOT, P_SEMICOLON, P_EOF,

    // Operators.
    OP_BANG, OP_BANG_EQUAL,
    OP_EQUAL, OP_EQUAL_EQUAL,
    OP_GREATER, OP_GREATER_EQUAL,
    OP_LESS, OP_LESS_EQUAL,
    OP_MINUS, OP_PLUS, OP_SLASH,
    OP_STAR, OP_PERCENT,

    // Literals.
    LIT_IDENTIFIER, LIT_STRING, LIT_INT, LIT_FLOAT, LIT_BOOLEAN,

    // Keywords.
    KW_AND, KW_CLASS, KW_ELSE, KW_FALSE, KW_FUNC, KW_FOR, KW_IF, KW_NULL, KW_OR,
    KW_RETURN, KW_TRUE, KW_WHILE, KW_VALUETYPE, KW_BREAK,

}