version: "3.8"

services:
  mc:
    container_name: minecraft_docker
    stdin_open: true
    tty: true
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.4"
      TYPE: "VANILLA"
    volumes:
      - ./mcdata:/data
