package compiler

import (
	"fmt"
	"github.com/Kolterdyx/mcbasic/internal/expressions"
	"github.com/Kolterdyx/mcbasic/internal/interfaces"
	"github.com/Kolterdyx/mcbasic/internal/parser"
	"github.com/Kolterdyx/mcbasic/internal/statements"
	"github.com/Kolterdyx/mcbasic/internal/tokens"
	"github.com/Kolterdyx/mcbasic/internal/visitors/compiler/ops"
	cp "github.com/otiai10/copy"
	log "github.com/sirupsen/logrus"
	"os"
	"path/filepath"
)

type Compiler struct {
	Config       interfaces.ProjectConfig
	Namespace    string
	DatapackRoot string

	functionsPath string
	tagsPath      string

	currentFunction statements.FunctionDeclarationStmt
	currentScope    string

	// functionArgs is a map of function names to their parameter names
	functionArgs map[string][]string
	// functionArgTypes is a map of function names to their parameter types. It matches the functionArgs map
	functionArgTypes map[string][]tokens.TokenType

	opHandler ops.Op

	expressions.ExprVisitor
	statements.StmtVisitor

	regCounter int
}

func (c *Compiler) Compile(program parser.Program) {
	err := c.createDirectoryTree()
	if err != nil {
		log.Fatalln(err)
	}
	c.createPackMeta()
	c.functionArgs = make(map[string][]string)
	c.functionArgTypes = make(map[string][]tokens.TokenType)
	for _, function := range program.Functions {
		c.functionArgs[function.Name.Lexeme] = make([]string, 0)
		for _, parameter := range function.Parameters {
			c.functionArgs[function.Name.Lexeme] = append(c.functionArgs[function.Name.Lexeme], parameter.Lexeme)
		}
		c.functionArgs[function.Name.Lexeme] = append(c.functionArgs[function.Name.Lexeme], "__call__")
		for _, argType := range function.Types {
			c.functionArgTypes[function.Name.Lexeme] = append(c.functionArgTypes[function.Name.Lexeme], argType.Type)
		}
		c.functionArgTypes[function.Name.Lexeme] = append(c.functionArgTypes[function.Name.Lexeme], tokens.NumberType)
	}
	// The opHandler is used to generate commands
	c.opHandler = ops.Op{Namespace: c.Namespace}
	// Traverse the AST to generate the functions
	for _, f := range program.Functions {
		f.Accept(c)
	}
	// Built-in functions are created after the user-defined functions to avoid overwriting them
	c.createBuiltinFunctions()
	c.createFunctionTags()
	err = cp.Copy(c.DatapackRoot, "/home/kolterdyx/.minecraft/saves/Test/datapacks/"+c.Config.Project.Name)
	if err != nil {
		log.Fatalln(err)
	}
}

func (c *Compiler) createDirectoryTree() error {
	c.Namespace = c.Config.Project.Namespace
	c.DatapackRoot, _ = filepath.Abs(c.Config.Project.Name)
	log.Infof("Compiling to %s\n", c.DatapackRoot)
	c.functionsPath = c.DatapackRoot + "/data/" + c.Namespace + "/functions"
	c.tagsPath = c.DatapackRoot + "/data/minecraft/tags"

	err := os.MkdirAll(c.functionsPath, 0755)
	err = os.MkdirAll(c.tagsPath, 0755)
	err = os.MkdirAll(c.functionsPath+"/builtin", 0755)
	return err
}

func (c *Compiler) createPackMeta() {
	packMcmeta := `{
	"pack": {
		"description": "Generated by mcbasic",
		"pack_format": 26
	}
}`
	err := os.WriteFile(c.DatapackRoot+"/pack.mcmeta", []byte(packMcmeta), 0644)
	if err != nil {
		log.Fatalln(err)
	}
}

func (c *Compiler) createBuiltinFunctions() {
	c.createFunction(
		"builtin/print",
		`$tellraw @a {"text":"$(text)"}`,
	)
	c.createFunction(
		"builtin/init",
		fmt.Sprintf("scoreboard objectives add %s dummy\n", c.Namespace)+
			c.opHandler.RegLoad("0", ops.CALL)+
			c.opHandler.Print("MCB pack loaded")+
			c.opHandler.Call("main"),
	)
}

func (c *Compiler) createFunction(name string, source string) {
	filename := name + ".mcfunction"
	err := os.WriteFile(c.functionsPath+"/"+filename, []byte(source), 0644)
	if err != nil {
		log.Fatalln(err)
	}
}

func (c *Compiler) createFunctionTags() {
	// load tag
	loadTag := `{
	"values": [
		"%s"
	]
}`
	err := os.MkdirAll(c.tagsPath+"/functions", 0755)
	if err != nil {
		log.Fatalln(err)
	}
	err = os.WriteFile(c.tagsPath+"/functions/load.json", []byte(fmt.Sprintf(loadTag, c.Namespace+":builtin/init")), 0644)
	if err != nil {
		log.Fatalln(err)
	}
}

func (c *Compiler) error(location interfaces.SourceLocation, message string) {
	log.Fatalf("Error at %d:%d: %s\n", location.Line, location.Column, message)
}

func (c *Compiler) newRegister(regName string) string {
	c.regCounter++
	return regName + fmt.Sprintf("%d$(__call__)", c.regCounter)
}
